package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"sync"
	"time"
)

// KeyVersion represents an active or deprecated signing key version.
type KeyVersion struct {
	ID        string
	Secret    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	IsActive  bool
}

// KeyRotationManager manages rotating HMAC/signature keys with seamless overlap periods.
type KeyRotationManager struct {
	mu           sync.RWMutex
	currentKeyID string
	keys         map[string]*KeyVersion
	keyTTL       time.Duration
	overlapGrace time.Duration
}

// NewKeyRotationManager creates a key manager.
func NewKeyRotationManager(keyTTL time.Duration, overlapGrace time.Duration) (*KeyRotationManager, error) {
	m := &KeyRotationManager{
		keys:         make(map[string]*KeyVersion),
		keyTTL:       keyTTL,
		overlapGrace: overlapGrace,
	}
	if err := m.Rotate(); err != nil {
		return nil, err
	}
	return m, nil
}

// Rotate creates a new primary key and deprecates the prior primary key while honoring grace overlap.
func (m *KeyRotationManager) Rotate() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	now := time.Now()
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return fmt.Errorf("failed to generate random secret: %w", err)
	}

	newID := fmt.Sprintf("key-%s", hex.EncodeToString(raw[:8]))

	// Demote existing active key
	if m.currentKeyID != "" {
		if prev, ok := m.keys[m.currentKeyID]; ok {
			prev.IsActive = false
			prev.ExpiresAt = now.Add(m.overlapGrace)
		}
	}

	m.keys[newID] = &KeyVersion{
		ID:        newID,
		Secret:    raw,
		CreatedAt: now,
		ExpiresAt: now.Add(m.keyTTL),
		IsActive:  true,
	}
	m.currentKeyID = newID
	return nil
}

// GetCurrentKey returns the active primary key for signing new payloads.
func (m *KeyRotationManager) GetCurrentKey() (*KeyVersion, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	key, ok := m.keys[m.currentKeyID]
	if !ok || !key.IsActive {
		return nil, fmt.Errorf("no active key available")
	}
	return key, nil
}

// VerifyKey checks if a signature was generated by the current or valid grace period key.
func (m *KeyRotationManager) VerifyKey(keyID string, candidateSecret []byte) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()

	key, ok := m.keys[keyID]
	if !ok {
		return false
	}

	if time.Now().After(key.ExpiresAt) {
		return false
	}

	return subtle.ConstantTimeCompare(key.Secret, candidateSecret) == 1
}

// PruneExpired removes keys past their grace expiration.
func (m *KeyRotationManager) PruneExpired() int {
	m.mu.Lock()
	defer m.mu.Unlock()

	now := time.Now()
	pruned := 0
	for id, k := range m.keys {
		if !k.IsActive && now.After(k.ExpiresAt) {
			delete(m.keys, id)
			pruned++
		}
	}
	return pruned
}
